### ISSUE TITLE
Tilemap loading

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/kajam2-dgc#2]

**Comment by coxm** [comment]
I've got the tiles loading on my branch (rebased on top of [mkalam-alami/master](https://github.com/mkalam-alami/kajam2-dgc/tree/master)).

Not sure if I broke the movement during the rebase or not. I couldn't get [mkalam-alami/master](https://github.com/mkalam-alami/kajam2-dgc/tree/master) working either but might be missing something. Shouldn't rule out PEBCAK on my part either :wink:

**Comment by mkalam-alami** [comment]
Nice work, it's now merged, featuring a cute rnlf now jumping around :)
